spring:
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  thymeleaf:
    check-template-location: false
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        globally-quoted-identifiers: true
    hibernate:
      ddl-auto: update
    sql:
      init:
        mode: always

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000